[tox]
env_list =
    py{311,312}
minversion = 4.11.3

[testenv]
description = run the tests with pytest
extras =
    hy
    dev
commands =
    pytest {tty:--color=yes} {posargs:tests}

[gh]
python =
    3.12 = py312
    3.11 = py311
