name: microkanren publishing

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    needs: test
    runs-on: ubuntu-latest

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: publish

    permissions:
      contents: none
      id-token: write # required for trusted publishing

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: pip install .[build]
      - name: Build package
        run: hatch build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
