name: microkanren publishing

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    permissions:
      contents: none
      id-token: write # required for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv venv
          uv sync --extra=dev
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
